# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40002915a5a097e1a8019138992781e120d2c9716f5e195c4db09dbabe0f83942c8ebbf27f38cb3c1407fb866d09a6ae8462f28fc86aab4e6a8e18a7a9135b2a

test:
  secret_key_base: 2dc40313ad4ba275e186205e1b2e7422a82e35c9ad0012736794c71e9568b2589fda9c46c28e61920613d36be1213d424c40c09d6fd43e478a6ff98d8bbfe0fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
